### ISSUE TITLE
Error  sending email

### ISSUE THREAD

**Issue by kalitk0** [s-ichikawa/laravel-sendgrid-driver#110]
Hello, I am getting the following error

`Argument 1 passed to App\Http\Controllers\WalletController::App\Http\Controllers\{closure}() must be an instance of App\Http\Controllers\Message, instance of Illuminate\Mail\Message given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php on line 242`

What can be the issue ?

**Comment by s-ichikawa** [comment]
Hi,
I think probably missing a proper "use" statement.
