### ISSUE TITLE
@s-ichikawa I'm unable to post `unique_args` using `embedData()`. You can see my Mailable code given below:

### ISSUE THREAD

**Issue by narendralussspacetech** [s-ichikawa/laravel-sendgrid-driver#112]
@s-ichikawa I'm unable to post `unique_args` using `embedData()`. You can see my Mailable code given below:

```
use SendGrid;
public function build()
{
return $this->from('support@domain.com', $from_name)
                    ->subject($subject)
                    ->markdown('email.review.review-request')
                    ->embedData(self::sgEncode([
                        'personalizations' => [
                            [
                                'substitutions' => [
                                    ':myname' => 'test',
                                ],
                            ],
                            'categories' => ['category_a_1', 'category_b_1'],
                        ],
                        'unique_args' => [
                            'user_id' => 'asdasdasdasdasd123'
                        ],
                        'categories' => ['category_a_1', 'category_b_1'],
                    ]), 'sendgrid/x-smtpapi');
}
```
I was check [ApiSimpleText.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimpleText.php), [ApiSimpleMailable.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimpleMailable.php), [ApiSimple.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimple.php) and [ApiMultiplePersonalizations.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiMultiplePersonalizations.php) before jump to here.

Could you please help me sort this out ASAP. :)

_Originally posted by @narendralussspacetech in https://github.com/s-ichikawa/laravel-sendgrid-driver/issues/75#issuecomment-577666515_

**Comment by s-ichikawa** [comment]
Hi, 
`unique_args` is probably for SMTP API.
https://sendgrid.com/docs/API_Reference/SMTP_API/unique_arguments.html

This library is using Web API v3. So you should use `custom_args` instead of `unique_args`.
see: https://sendgrid.kke.co.jp/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by narendralussspacetech** [comment]
@s-ichikawa Thanks for quick reply. I tried each ways but still stuck at unknown point.

**Comment by s-ichikawa** [comment]
I tried as following:
https://github.com/s-ichikawa/laravel60/blob/7da736c07607763df5b16e36955dce7c67ea3f9d/app/Console/Commands/Mail/ApiSimpleMultiTo.php#L71-L78

and confirmed to work well in Sendgrid Activity Page.
<img width="486" alt="スクリーンショット 2020-01-24 0 44 38" src="https://user-images.githubusercontent.com/3357107/72999471-c4476b80-3e42-11ea-86d1-bb0002a43b65.png">

**Comment by jackbaron** [comment]
@s-ichikawa How can I get status when sending mail successfully? Thanks
List status response send mail using smtp: 
https://sendgrid.com/docs/API_Reference/SMTP_API/errors_and_troubleshooting.html

**Comment by s-ichikawa** [comment]
@jackbaron You can't it now.
You can get Message-ID via `sendPerformed()` and search results at Sendgrid Activity page instead. 
see: https://github.com/s-ichikawa/laravel-sendgrid-driver/issues/100#issuecomment-499091669
