### ISSUE TITLE
Support IP pool specification

### ISSUE THREAD

**Issue by mpyw** [s-ichikawa/laravel-sendgrid-driver#113]
Currently I'm using the following dirty hack for achieving emails from IP pool.

- [【Laravel】 Mailable から SendGrid の IP プールを指定できるようにする - Qiita](https://qiita.com/mpyw/items/d308790295d19436091d)

It can be better that we officially support this feature in more proper way.

**Comment by s-ichikawa** [comment]
Basically Parameters of Mail API v3 can be passed like the following Sample, but Didn't ip_pool_name work well?
https://github.com/s-ichikawa/laravel-sendgrid-driver#use-in-mailable

**Comment by mpyw** [comment]
Sorry I was missing that method! Thanks
