### ISSUE TITLE
cURL error 18: transfer closed with remaining bytes

### ISSUE THREAD

**Issue by rognales** [s-ichikawa/laravel-sendgrid-driver#114]
Hi there,

I'm getting this error. I'm using basic Mailable Laravel function.
My stacks:-

- Laravel Framework 6.16.0
- guzzlehttp/guzzle": "^6.3"
- s-ichikawa/laravel-sendgrid-driver": "^2.1

````sh
local.ERROR: cURL error 18: transfer closed with 116 bytes remaining to read (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 
{"userId":1,"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 401): 
cURL error 18: transfer closed with 116 bytes remaining to read (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at C:\\laragon\\www\\familyday\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:201)
````
This is my mailable class.

````php
public function build()
{
  return $this->subject('Family Day 2020 Registration Confirmation')
    ->view('registration.litmus');
}
````

**Comment by s-ichikawa** [comment]
hmm... I saw the same issue(https://github.com/s-ichikawa/laravel-sendgrid-driver/issues/109) before.
Maybe this is a problem with your host further than this library.
Please check your server setting (e.g. version of PHP, curl, etc...)

**Comment by Expertweblancer** [comment]
Same issue
any solution?

**Comment by s-ichikawa** [comment]
It is probably there is a problem of a network. 
I think good to consult with the person in charge of infrastructure first.

rel: https://stackoverflow.com/questions/1759956/curl-error-18-transfer-closed-with-outstanding-read-data-remaining
rel: https://github.com/guzzle/guzzle/issues/1600

**Comment by s-ichikawa** [comment]
or It may good to try this(https://justrocketscience.com/post/php_guzzle_bug/).

**Comment by djabdou50** [comment]
in my case, it was just sendgrid api keys that was reseted, just ensure that keys are correct first before change anything :)
