### ISSUE TITLE
"Undefined index: transport" for Laravel 7

### ISSUE THREAD

**Issue by daanadriaan** [s-ichikawa/laravel-sendgrid-driver#115]
After upgrading to Laravel 7 I get the following error when sending e-mail:

Mailing in Laravel 7 has changes, any idea how to solve this?

PHP Notice:  Undefined index: transport in /Sites/website/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 174
InvalidArgumentException with message 'Unsupported mail transport [].'

**Comment by s-ichikawa** [comment]
I started to migrate for Laravel 7 (https://github.com/s-ichikawa/laravel-sendgrid-driver/pull/116).
Please wait for the merge. (or try with dev branch.)
thanks!

**Comment by daanadriaan** [comment]
You're the best <3

**Comment by s-ichikawa** [comment]
Merged into master and create tag `3.0.0`.
enjoy sendgrid!
Thank you for a nice issue.
