### ISSUE TITLE
Connection could not be established

### ISSUE THREAD

**Issue by carrera** [s-ichikawa/laravel-sendgrid-driver#118]
Locally the sendgrid connection works without any problem but when published on Azure I get this error:

`Swift_TransportException`

`
Connection could not be established with host smtp.urlremoved.com :stream_socket_client(): unable to connect to smtp.urlremoved.com:2525 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. )
`

**Comment by s-ichikawa** [comment]
Sorry, I have never used the Azure environment, so I can't try.
But looks to be used `smtp`.
Maybe configuration is not well. so try to check `.env` file.
