### ISSUE TITLE
Cannot install the package from composer

### ISSUE THREAD

**Issue by fredchantp** [s-ichikawa/laravel-sendgrid-driver#121]
Error when composer require s-ichikawa/laravel-sendgrid-driver

s-ichikawa/laravel-sendgrid-driver 3.0.0 requires illuminate/mail >=7.0
Can only install one of: laravel/framework[7.x-dev, v6.9.0].

Laravel version 6.9.0

**Comment by s-ichikawa** [comment]
Please set `~2.0` version.
```
$ composer require s-ichikawa/laravel-sendgrid-driver=~2.0
```

**Comment by BaiMaoLi** [comment]
Why it should be 2.0? 
your 3.o version have issue?

**Comment by s-ichikawa** [comment]
https://github.com/s-ichikawa/laravel-sendgrid-driver/issues/123#issuecomment-625878472
