### ISSUE TITLE
Unauthorized when email is queued.

### ISSUE THREAD

**Issue by trd-warren** [s-ichikawa/laravel-sendgrid-driver#122]
Everything works fine when using `sync` as QUEUE_DRIVER.
But then I decided to queue my events in database.

But I got problem.
Other queues are working.

In case mail with Email

```
 Mail::to($to_Email)
            ->send(new StatusChangeMail($data));
```

It is working. So I need to queue.

```
 Mail::to($to_Email)
            ->queue(new StatusChangeMail($data));
```

But then, email failed_job in DB saying 

```
GuzzleHttp\Exception\ClientException: Client error: `POST https://api.sendgrid.com/v3/mail/send` resulted in a `401 Unauthorized` response:
{"errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null}]}
 in /var/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

All configs are correct. Maybe I missed something?

Version: 2.1.0

**Comment by s-ichikawa** [comment]
Is API_KEY correctly passed to the transporter?
There are several possible causes:
- Queue listener is working another env, and there is not configured the API_KEY.
- The queue listener's process is working before the API_KEY was set. In this case, should restart the queue listener process.

My environment can work by database queue at least.

**Comment by trd-warren** [comment]
> * The queue listener's process is working before the API_KEY was set. In this case, should restart the queue listener process.

@s-ichikawa 

Ahh, the environment is deployed in ElasticBeanstalk.
I have commands  that installs and runs supervisor first then config:cache.
Probably the cause?

**Comment by trd-warren** [comment]
@s-ichikawa 

And by the way, API was written to server.
```php
return [
    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, SparkPost and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */
    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
    ],
    'ses' => [
        'key' => env('SES_KEY'),
        'secret' => env('SES_SECRET'),
        'region' => 'us-east-1',
    ],
    'sparkpost' => [
        'secret' => env('SPARKPOST_SECRET'),
    ],
    'stripe' => [
        'model' => \App\Models\User::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],
    'sendgrid' => [
        'api_key' =>  $_SERVER['API_KEY'],
    ],
];
```

**Comment by s-ichikawa** [comment]
> Ahh, the app is deployed to ElasticBeanstalk.
I have commands that installs and runs supervisor first then config:cache.
Probably the cause?

I don't have an ElasticBeanstalk environment and can't try it.
But It's worth trying `config:cache` 👍

**Comment by trd-warren** [comment]
> * The queue listener's process is working before the API_KEY was set. In this case, should restart the queue listener process.

@s-ichikawa 

Thank you so much. My problem was that the queue worker was started before all config files are ready. Restarting the queue worker after the config:cache solved my issue. You can close this issue now.
