### ISSUE TITLE
Why it supports Laravel 7 onwards only?

### ISSUE THREAD

**Issue by ilyaskazi** [s-ichikawa/laravel-sendgrid-driver#123]
In the view of many applications which were built using Laravel 5 and 6 also as they remain long famous.. isn't this library/package should support those versions. 

Or even though if not possible because of legacy codes that doubts the compatibility one should think of keeping it separate. 

Do you hv any plan to keep separate or keep both compatible in same repo please?

**Comment by s-ichikawa** [comment]
Because In Laravel 7, it has been made an [incompatible change at laravel/framework](https://github.com/laravel/framework/pull/31073/files#diff-025006b2c4889f2136ad802e7ee2f622). So I had no choice but to support only ^7.0.
But I think to continue to support the lower version by `2.x` tag.
