### ISSUE TITLE
Please support v3 Mail Send

### ISSUE THREAD

**Issue by thinkingserious** [s-ichikawa/laravel-sendgrid-driver#13]
References:
- https://github.com/sendgrid/sendgrid-php
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thank you for creating this library!

Please let me know if you run into any issues :)

Please send us an email at dx@sendgrid.com with your mailing address and T-shirt size so we can send you a small token of our appreciation.

**Comment by s-ichikawa** [comment]
Thank you for your proposal.

I added improvement for v3 mail send !
How does that look?

**Comment by thinkingserious** [comment]
Thank you for taking the time to implement this!

I have one suggestion. Since the SMTPAPI header is now included in the v3 /mail/send endpoint, you might want to use a new variable name [here](https://github.com/s-ichikawa/laravel-sendgrid-driver/blob/master/src/Transport/SendgridV3Transport.php#L167) to avoid confusion.

**Comment by s-ichikawa** [comment]
Thank you, I just fixed! @cb93574
