### ISSUE TITLE
Error install requires illuminate/mail >=7.0

### ISSUE THREAD

**Issue by Jorge-Ivan** [s-ichikawa/laravel-sendgrid-driver#130]
I trie install package with error: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - s-ichikawa/laravel-sendgrid-driver 3.0.1 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.
    - s-ichikawa/laravel-sendgrid-driver 3.0.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for s-ichikawa/laravel-sendgrid-driver ^3.0 -> satisfiable by s-ichikawa/laravel-sendgrid-driver[3.0.0, 3.0.1, 3.0.2].
    - Conclusion: remove laravel/framework v5.5.49
    - Conclusion: don't install laravel/framework v5.5.49
    - s-ichikawa/laravel-sendgrid-driver 3.0.2 requires illuminate/mail >=7.0 -> satisfiable by illuminate/mail[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/mail v7.0.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.3|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.4|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.5|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.6|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.7|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.0.8|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.1.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.1.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.1.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.1.3|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.10.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.10.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.10.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.10.3|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.11.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.12.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.13.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.14.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.14.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.15.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.16.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.16.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.17.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.17.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.17.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.18.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.19.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.19.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.2.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.2.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.2.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.20.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.21.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.22.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.22.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.22.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.22.3|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.22.4|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.23.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.3.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.4.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.5.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.5.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.5.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.6.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.6.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.6.2|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.7.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.7.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.8.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.8.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.9.0|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.9.1|don't install laravel/framework v5.5.49
    - don't install illuminate/mail v7.9.2|don't install laravel/framework v5.5.49
    - Installation request for laravel/framework (locked at v5.5.49, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.49].

composer.json

`{`
`    "name": "laravel/laravel",`
`    "description": "The Laravel Framework.",`
`    "keywords": ["framework", "laravel"],`
`    "license": "MIT",`
`    "type": "project",`
`    "require": {`
`        "php": ">=7.0.0",`
`        "barryvdh/laravel-snappy": "^0.4.7",`
`        "crazybooot/base64-validation": "^1.0",`
`        "fideloper/proxy": "~3.3",`
`        "guzzlehttp/guzzle": "^7.0",`
`        "laravel/framework": "5.5.*",`
`        "laravel/tinker": "~1.0",`
`        "ramsey/uuid": "~3.0",`
`        "spatie/laravel-permission": "~2.38.0"`
`    },`
`    "require-dev": {`
`        "filp/whoops": "~2.0",`
`        "fzaninotto/faker": "~1.4",`
`        "mockery/mockery": "~1.0",`
`        "phpunit/phpunit": "~6.0",`
`        "symfony/thanks": "^1.0"`
`    },`
`    "autoload": {`
`        "files": [`
`            "app/Http/Helpers.php"`
`        ],`
`        "classmap": [`
`            "database/seeds",`
`            "database/factories"`
`        ],`
`        "psr-4": {`
`            "App\\": "app/"`
`        }`
`    },`
`    "autoload-dev": {`
`        "psr-4": {`
`            "Tests\\": "tests/"`
`        }`
`    },`
`    "extra": {`
`        "laravel": {`
`            "dont-discover": [`
`            ]`
`        }`
`    },`
`    "scripts": {`
`        "post-root-package-install": [`
`            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""`
`        ],`
`        "post-create-project-cmd": [`
`            "@php artisan key:generate"`
`        ],`
`        "post-autoload-dump": [`
`            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",`
`            "@php artisan package:discover"`
`        ]`
`    },`
`    "config": {`
`        "preferred-install": "dist",`
`        "sort-packages": true,`
`        "optimize-autoloader": true`
`    }`
`}`

**Comment by s-ichikawa** [comment]
master or `~3.0` are for `laravel >=7.0`.
Please try using a version of `~2.0`.

**Comment by Jorge-Ivan** [comment]
Error with version guzzlehttp/guzzle `^7.0` in laravel `5.5.*`

Problem 1
    - s-ichikawa/laravel-sendgrid-driver 2.1.0 requires guzzlehttp/guzzle ~5.3|~6.2 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.x-dev, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by s-ichikawa** [comment]
I fixed this problem. It seems to fine now.
```
$ php artisan -V
Laravel Framework 5.5.49
$ cat composer.json| grep guzzle
        "guzzlehttp/guzzle": "~7.0",
$ composer require s-ichikawa/laravel-sendgrid-driver:~2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing s-ichikawa/laravel-sendgrid-driver (2.1.1): Loading from cache
...
Discovered Package: s-ichikawa/laravel-sendgrid-driver
Package manifest generated successfully.
31 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

Thank you.
