### ISSUE TITLE
Error sending email  cURL error 18: transfer closed with 116

### ISSUE THREAD

**Issue by atiladelcanton** [s-ichikawa/laravel-sendgrid-driver#137]
Good Morning!

Recently I started to have a problem with sending e-mail with sendgrid, it just has a time that it will not and returns the following error:

```sh
cURL error 18: transfer closed with 116 bytes remaining to read (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 401): cURL error 18: transfer closed with 116 bytes remaining to read (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/html/app.fontecred.com.br/system/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186)
```

can you help me?

**Comment by twarkie** [comment]
I got this exact message when I accidentally used the incorrect key. Worth a double check.

**Comment by atiladelcanton** [comment]
It has already been seen, the key has been changed and time goes by and time for this error. :(

**Comment by s-ichikawa** [comment]
This issue has been reported several times before. but this cause may be on the network layer or your server setting. so it is difficult to resolve in this library.
If it happens very frequently, you should ask your SRE or infra team.
Sorry, I can't help...
