### ISSUE TITLE
InvalidArgumentException - Unsupported mail transport [sendgrid].

### ISSUE THREAD

**Issue by msamgan** [s-ichikawa/laravel-sendgrid-driver#139]
In spite of doing everything as per documentation, i am not able to fire mails in laravel 7.
getting the following error.

Can you please help as in my project SMTP configuration with sendgrid is taking some time to deliver mail. so i decided to switch to API but i am facing the following issue and it seems like there is no available on google for this.

![image](https://user-images.githubusercontent.com/29948727/100581059-8045b280-3300-11eb-842a-ef68e8a36a32.png)

**Comment by s-ichikawa** [comment]
Did you run `composer install`? It seems to be not loaded the library well.

**Comment by msamgan** [comment]
yes,
i also went through the service provider.
->afterResolving function, the code is there but i dont know why its not working.
its not passing the custom transporter.
I am using laravel Laravel Framework 7.29.3

**Comment by s-ichikawa** [comment]
I think the `config/mail.php` may be incorrect. Is the setting correct?
see: https://github.com/s-ichikawa/laravel70/blob/master/config/mail.php#L64-L67

**Comment by msamgan** [comment]
but the Read me says to add it like this..

'mailers' => [
        'sendgrid' => [
            'transport' => 'sendgrid',
        ],
    ],

i did it like that.
are you saying this is the issue ..????

**Comment by s-ichikawa** [comment]
No, I want to confirm you did NOT wrong.
If your config is written as follows, it will happen the same error:
```
<?php

return [
    ...
    'mailers' => [
        'smtp' => [
            'transport' => 'smtp',
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
            'auth_mode' => null,
        ],

        'ses' => [
            'transport' => 'ses',
        ],

        'mailgun' => [
            'transport' => 'mailgun',
        ],

        'postmark' => [
            'transport' => 'postmark',
        ],

        'sendmail' => [
            'transport' => 'sendmail',
            'path' => '/usr/sbin/sendmail -bs',
        ],

        'log' => [
            'transport' => 'log',
            'channel' => env('MAIL_LOG_CHANNEL'),
        ],

        'array' => [
            'transport' => 'array',
        ],

        'mailers' => [
            'sendgrid' => [
                'transport' => 'sendgrid',
            ],
        ],
    ],
```

**Comment by s-ichikawa** [comment]
Or didn't add `MAIL_MAILER=sendgrid` in `.env`?
https://github.com/s-ichikawa/laravel-sendgrid-driver/blob/master/README.md#configure

**Comment by rafi-isakh** [comment]
@s-ichikawa I happened to face the same error with Lumen v7.2.2
Here is my config and .env file
```
<?php

return [
    ....
    'mailers' => [
      'sendgrid' => [
        'transport' => 'sendgrid',
      ]
    ]
]

```

```
MAIL_DRIVER=sendgrid
SENDGRID_API_KEY=<myAPI key>
MAIL_MAILER=sendgrid
```
do I miss something for the configuration?

**Comment by s-ichikawa** [comment]
Is the parent of 'mailers' 'return'?
Make sure it doesn't look like this:
```
// Wrong:
return [
    ....
    'mailers' => [
        ...
        'mailers' => [
            'sendgrid' => [
                'transport' => 'sendgrid',
            ],

// Right:
return [
    'mailers' => [
        'sendgrid' => [
            'transport' => 'sendgrid',
        ],
```

**Comment by rafi-isakh** [comment]
Yes, just like the example that I posted.  The parent is array return and I only define mailers once

**Comment by s-ichikawa** [comment]
In the lumen, you should register the service provider via bootstrap/app.php. Is it complete?

And I created a sample repository:
https://github.com/s-ichikawa/lumen7/blob/main/bootstrap/app.php#L97-L101

**Comment by rafi-isakh** [comment]
I think I have set it correctly. Please take a look at my `bootstrap/app.php`

```
/*
|--------------------------------------------------------------------------
| Register Config Files
|--------------------------------------------------------------------------
|
| Now we will register the "app" configuration file. If the file exists in
| your configuration directory it will be loaded; otherwise, we'll load
| the default version. You may register other files below as needed.
|
*/

$app->configure('app');
$app->configure('services');
$app->configure('mail');

/*
|--------------------------------------------------------------------------
| Register Service Providers
|--------------------------------------------------------------------------
|
| Here we will register all of the application's service providers which
| are used to bind services into the container. Service providers are
| totally optional, so you are not required to uncomment this line.
|
*/

$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\AuthServiceProvider::class);
$app->register(\Illuminate\Auth\Passwords\PasswordResetServiceProvider::class);
// $app->register(App\Providers\EventServiceProvider::class);

$app->register(Tymon\JWTAuth\Providers\LumenServiceProvider::class);
$app->register(BenSampo\Enum\EnumServiceProvider::class);
$app->register(Illuminate\Notifications\NotificationServiceProvider::class);
$app->alias('mail.manager', Illuminate\Contracts\Mail\Factory::class);
$app->register(Sichikawa\LaravelSendgridDriver\MailServiceProvider::class);

unset($app->availableBindings['mailer']);
```

**Comment by s-ichikawa** [comment]
Ahh, may you be using the 2.0.x?
If so, please update this library to `^3.0`.

You should use the version of this library `^3.0` from the lumen-framework `>=7.0`.
The README makes a mistake. So I'll correct it in few days.

**Comment by rafi-isakh** [comment]
Alright, thank you
It is working perfectly after I change it into version `^3.0`
