### ISSUE TITLE
Error - Expected: object, given: array

### ISSUE THREAD

**Issue by cimd** [s-ichikawa/laravel-sendgrid-driver#140]
Hi,

I'm using Laravel 7 and getting this error message:

"GuzzleHttp\Exception\ClientException
Client error: `POST https://api.sendgrid.com/v3/mail/send` resulted in a `400 Bad Request` response: {"errors":[{"message":"Invalid type. Expected: object, given: array.","field":"from","help":"http://sendgrid.com/docs/AP (truncated...)"

I'm using a very simple test case, like this: "https://codegits.com/sendgrid-laravel-mail/"

**Comment by s-ichikawa** [comment]
Please confirm configure about the `from` in config/mail.php.

**Comment by cimd** [comment]
You were right. I had migrated from Laravel 6 to Laravel 7 so I can use this package and the mail.php from laravel 6 is a bit different. Upgrading the file to the Laravel 7 standard fixed the issue. Thanks.
