### ISSUE TITLE
Way to get SendGrid's Message ID

### ISSUE THREAD

**Issue by itailulu** [s-ichikawa/laravel-sendgrid-driver#146]
Is there any way to retrieve the message ID from SendGrid?

**Comment by s-ichikawa** [comment]
Hi, You can use Swift_Events_SendListener via registerPlugin.
see: https://github.com/s-ichikawa/laravel70/blob/master/app/Console/Commands/Mail/ApiSimple.php#L49

**Comment by repat** [comment]
@s-ichikawa Is there any way we can do this with the Symfony Mailer as well?
