### ISSUE TITLE
Can't pass custom_args in Laravel notifications (using MailMessage)

### ISSUE THREAD

**Issue by amouillard** [s-ichikawa/laravel-sendgrid-driver#147]
I'm using sendgrid to send notification emails. My goal is adding custom_args to outgoing notification emails so I can identify the subsequent SendGrid event webhooks.
I have extended the base Illuminate\Notifications\Messages\MailMessage class as such :

```
<?php

namespace App\Bin\Notifications;

use Illuminate\Notifications\Messages\MailMessage;
use Sichikawa\LaravelSendgridDriver\SendGrid;

class SendgridMailMessage extends MailMessage
{
    use SendGrid;

    public $notifiable;

    public function __construct($notifiable)
    {
        return $this->sendgrid([
                'custom_args' => [
                    'user_id' => "testing_testing",
                ],
        ])
            ->from(env('FROM'), env('FROM_NAME'));
    }
}
```

I'm not sure if the SendGrid trait is the right use case here. I've also tried : 

```
$headerData = [
        'custom_args' => [
           'user_id' => "testing_testing",
        ],
];

return $this->withSwiftMessage(function ($message) use ($headerData) {
    $message->getHeaders()
        ->addTextHeader('X-SMTPAPI', json_encode($headerData));
})
```

In both cases, the SendGrid API does not receive the custom_args passed. No errors are thrown.

**Comment by amouillard** [comment]
The SendGrid trait works but requires a small change for use with notifications MailMessage.

I've added #148 

Not sure if it's the correct way but it does work.

**Comment by Robertkeli** [comment]
Hey guys, where should the sendgrid method be called in?

I got this error when I called it inside the `toMail($notifiable)` method?

```
return (new MailMessage)
            ->subject($emailSubject)
            ->markdown('Email.reviewSubmittedMerchant')
	    ->sendgrid([
            'custom_args' => [
                'category' => 'review-received-merchant-email',
                'ss_message_id' => $this->messageId,
                'email_code' => $this->reviewCode
            ],
        ]);
```

**Error: Call to undefined method Illuminate\Notifications\Messages\MailMessage::sendgrid()**

Calling the method from the constructor also didn't yield any results, I never got my custom arguments in my webhooks. What's the correct way to do it?

**Comment by Robertkeli** [comment]
Absolutely fantastic, did a few edits and it works perfectly for me. Thanks a lot mate. Your help is highly appreciated.

**Comment by Robertkeli** [comment]
Hi @amouillard and @s-ichikawa , I recently upgraded my application to Laravel 9, which uses Symfony Mailer instead of  Swift Mailer. I have been refactoring my code to reflect those changes, but I'm stuck here

```
<?php

use Illuminate\Notifications\Messages\MailMessage;
use Sichikawa\LaravelSendgridDriver\SendGrid;
use Sichikawa\LaravelSendgridDriver\Transport\SendgridTransport;
use Symfony\Component\Mime\Email;

class SendGridMail extends MailMessage
{
    use Sendgrid;

    /**
     * Custom arguments
     *
     * @var array
     */
    public $customArgs;

    /**
     * New SendGridMail instance
     *
     * @param array $customArgs
     */
    public function __construct($customArgs)
    {
        return $this->withSymfonyMessage(function (Email $message) use ($customArgs) {
            $message->embed(new \Swift_Image(
                static::sgEncode($customArgs),
                SendgridTransport::SMTP_API_NAME
            ));
        });
    }
}

```
![symfony-mailer](https://user-images.githubusercontent.com/10114284/187105483-998c9631-1fed-4d9e-b73d-e16cacb91a35.png)


Do you have an idea how to pass the custom args to the embed method?

**Comment by s-ichikawa** [comment]
Hi, I think you don't need to make Swift_Image.
I could send an email with customArgs by this way.

```
        return $this->withSymfonyMessage(function (Email $message) use ($customArgs) {
            $message->embed(static::sgEncode($customArgs), SendgridTransport::REQUEST_BODY_PARAMETER);
        });
```

**Comment by Robertkeli** [comment]
Thank you so much @s-ichikawa , it works perfectly 👌
