### ISSUE TITLE
Empty email, when using template ID

### ISSUE THREAD

**Issue by dominik-wbz** [s-ichikawa/laravel-sendgrid-driver#149]
Hi, in my mailable I have 

```
return $this->view([])
            ->sendgrid([
                'personalizations' => [
                    [
                        'substitutions' => [
                            ':myname' => 's-ichikawa',
                        ],
                    ],
                ],
                'template_id' => 'd-c19e90f50ec2455489ab4e1566e909c0',
            ]);

```
It send's the email but is empty, also subject is default laravel mailable name. I have the template created in my sendrid acc. Any idea why this doesnt work?

**Comment by s-ichikawa** [comment]
Hmm, I tried some patterns but could not reproduce them.
Are the mail surely send via SendGrid? Please confirm it from SendGrid's Activity Feed.

**Comment by dominik-wbz** [comment]
yes, I can confirm its sending via SendGrid
![Screenshot 2021-02-03 at 14 21 37](https://user-images.githubusercontent.com/8103258/106752860-34c6c200-662b-11eb-9734-24123c0d7770.png)

**Comment by s-ichikawa** [comment]
> Substitutions allow you to insert data when not using Dynamic Transactional Templates. This field should not be used in combination with a dynamic transactional template, which can be identified by a template_id starting with d-.
https://sendgrid.com/docs/api-reference/

From the official API reference, `substitutions` can NOT use with Dynamic Transactional Templates. 


Please check your usage.

**Comment by s-ichikawa** [comment]
I think you should use `dynamic_template_data` when using the Dynamic Transactional Templates.

my sample: https://github.com/s-ichikawa/laravel8/blob/032d7b1fcaa13bfe321fe0f5c44c2e5a88fdb1bf/app/Mail/ApiSimpleMailable.php#L41

**Comment by dominik-wbz** [comment]
Thank you for your replies, I've now replaced my code with your sample, but it's sending an empty email anyways.. So, you are recieving an email template (created in sendgrid) with content provided by your example?

**Comment by s-ichikawa** [comment]
Yes, my example has applied the template...
If you can edit the code in the vendor directory, you can edit `vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php` like a following for checking data to send:
```
69        $payload = [
70            'headers' => [
71                'Authorization' => 'Bearer ' . $this->apiKey,
72                'Content-Type' => 'application/json',
73            ],
74            'json' => $data,
75        ];
76 +    var_dump($payload);

```

**Comment by dominik-wbz** [comment]
Thank you very much for the pointers, I got it working now with your example.

**Comment by ghidoz** [comment]
@dominik-wbz How did you solve it? I have the same error and I'm just using the example:

`
$data = ['url' => $url, 'name' => $user->name];
Mail::send([], [], function (Message $message) use ($user, $data) {
    $message
        ->to($user->email)
        ->embedData(json_encode([
            'personalizations' => [
                [
                    'dynamic_template_data' => $data
                ],
            ],
            'template_id' => config('services.sendgrid.templates.password_recovery'),
        ]), SendgridTransport::SMTP_API_NAME);
});
`

but I keep receiving an empty email (sent by SendGrid as I can see in the activity).


> Yes, my example has applied the template...
> If you can edit the code in the vendor directory, you can edit `vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php` like a following for checking data to send:
> 
> ```
> 69        $payload = [
> 70            'headers' => [
> 71                'Authorization' => 'Bearer ' . $this->apiKey,
> 72                'Content-Type' => 'application/json',
> 73            ],
> 74            'json' => $data,
> 75        ];
> 76 +    var_dump($payload);
> ```

@s-ichikawa I did it, but it doesn't print anything. It looks like it doesn't pass through your send method.

I'm using Laravel 7, so it should discover the package automatically, right? I even tried adding the service provider to the config/app.php list but with no luck.

Any ideas?

**Comment by sajumani** [comment]
Am also getting empty mail when i using template id

Anything am i missing ?
