### ISSUE TITLE
Remove File Size Limit validation for v1

### ISSUE THREAD

**Issue by Edwinws** [s-ichikawa/laravel-sendgrid-driver#151]
Recently these pull requests were merged:
- https://github.com/s-ichikawa/laravel-sendgrid-driver/pull/143
- https://github.com/s-ichikawa/laravel-sendgrid-driver/pull/142

Can we also make these changes to version 1? My company's project uses Laravel 5.4 and we are unable to update to newer versions at this time.

Alternatively, if a 1.x branch is created I would submit a pull request.

**Comment by s-ichikawa** [comment]
Fix it in 1.x branch and pushed 1.2.7 !

**Comment by Edwinws** [comment]
Thank you!
