### ISSUE TITLE
str_random() method in tests for Laravel 5.8 and higher

### ISSUE THREAD

**Issue by hejingyuan199** [s-ichikawa/laravel-sendgrid-driver#156]
Hi,

testXMessageID() in laravel-sendgrid-driver/tests/Transport/SendgridTransportTest.php
It uses "str_random()". But it is not a php function, but a Laravel helper function.
From Laravel 5.8 and higher(6.*, 7.*, 8.*), it is changed to Illuminate/Support/Str::random()
So, just let you know.

You can refer to:
https://laravel.com/docs/6.x/upgrade#helpers

    public function testXMessageID()
    {
        $client = $this->getMockBuilder(\GuzzleHttp\Client::class)
            ->onlyMethods(['request'])
            ->getMock();
        $transport = new SendgridTransport($client, $this->api_key);

        $messageId = str_random(32);
        $client->expects($this->once())
            ->method('request')
            ->willReturn(new \GuzzleHttp\Psr7\Response(200, [
                'X-Message-ID' => $messageId,
            ]));
        $message = new Message($this->getMessage());
        $message->from('from@google.com', 'test_from')
            ->to('to@sink.sendgrid.net', 'test_to');
        $transport->send($message->getSwiftMessage());
        $this->assertEquals($messageId, $message->getSwiftMessage()->getHeaders()->get('X-Sendgrid-Message-ID')->getFieldBody());
    }

**Comment by s-ichikawa** [comment]
I fixed it.
Thank you!
