### ISSUE TITLE
Laravel9 support

### ISSUE THREAD

**Issue by s-ichikawa** [s-ichikawa/laravel-sendgrid-driver#160]
I'm working on making support the laravel v9 now.
https://github.com/s-ichikawa/laravel-sendgrid-driver/pull/159

There was a big change in the mail component from laravel9.
https://github.com/laravel/framework/pull/38481

But  I'm not using the laravel recently. so please try the [for_laravel9](https://github.com/s-ichikawa/laravel-sendgrid-driver/tree/for_laravel9) branch and create an issue if you face some problems.

If there is no critical issue until 2/22/2022, I'll merge into master branch and tag `4.0.0`.

**Comment by kustomrtr** [comment]
Hey, thanks for the update. I've been testing the `for_laravel9` branch and so far it's been working great!

**Comment by s-ichikawa** [comment]
@kustomrtr Thank you for your trial and reporting.
I'd like to make sure, that's when you try to install it on Laravel instead of [Lumen](https://lumen.laravel.com/), right?
These configure are for the installation of Lumen.

**Comment by kustomrtr** [comment]
@s-ichikawa omg I feel stupid now, I re-checked the readme and you're in fact right. I was adding those Lumen settings on a Laravel installation, I'm blind hahaha. Thanks again!

**Comment by s-ichikawa** [comment]
OK, Thank you for your trying!

**Comment by rjp-thijs** [comment]
Also going to test this out! I did notice a small issue while upgrading:

We're using the `SendgridTransport::SMTP_API_NAME` constant, which doesn't exist anymore. Changed it to `SendgridTransport::REQUEST_BODY_PARAMETER`

**Comment by s-ichikawa** [comment]
@rjp-thijs  Ahh, yes. I changed that const name.
It might have been a bit rough as a way to change the const name. For the time being, leave SMTP_API_NAME as well and deprecate it.
Thank you!

**Comment by rjp-thijs** [comment]
Just wanted to report back that we've been using this in production for about a week now and havent noticed any issues :)

**Comment by Koozza** [comment]
@s-ichikawa Migtht have cheered a bit too early. It seems that something messes up with our attachments. I'm going to dive into this issue now, but I just wanted to pre-warn you :) PDF and XML attachments get attached as they should, but our CSV's are added as plain text below the mail.

**Comment by s-ichikawa** [comment]
@Koozza Fixed it!
Thank you very much!

**Comment by Koozza** [comment]
I would be fine with releasing this as 1.4 :) Haven't noticed any other bugs!

**Comment by s-ichikawa** [comment]
I merged #159 and tagged `4.0.0`.
@kustomrtr @rjp-thijs @Koozza 
Thank you very much for your contributions!
