### ISSUE TITLE
Issue with the `attachments` element in the array passed to `sendgrid` method

### ISSUE THREAD

**Issue by l-alexandrov** [s-ichikawa/laravel-sendgrid-driver#161]
Currently when we pass an element with `attachments` key in the array to the `sendgrid` method and send the email we receive:

> array_merge(): Argument #1 must be of type array, null given
> 
>  /srv/some-fancy-app/vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php(243): array_merge()
> #1 /srv/some-fancy-app/vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php(76): Sichikawa\LaravelSendgridDriver\Transport\SendgridTransport->setParameters()
> #2 /srv/some-fancy-app/vendor/symfony/mailer/Transport/AbstractTransport.php(68): Sichikawa\LaravelSendgridDriver\Transport\SendgridTransport->doSend()
> #3 /srv/some-fancy-app/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Symfony\Component\Mailer\Transport\AbstractTransport->send()

Example code:
```
 public function build()
 {
      $sendGridPayload = [
                  'attachments' => ['content' => '...', 'filename' => '...', 'type' => '...']
      ];
        return $this
            ->subject('...')
            ->sendgrid($sendGridPayload);
}
```

I think the issue is when adding support to Laravel 9 [you've removed the `attachments` class member initialization](https://github.com/s-ichikawa/laravel-sendgrid-driver/commit/29aa94aeb9d1396c1e446ec280ea9572404a465d#diff-64185c68b369b4bab0b950fef50d37606ebbad68f69d585a148b93c234a59653R202) and now it remains uninitalized.

**Comment by s-ichikawa** [comment]
Merged it and tagged `4.0.1`.
Thank you for fixed!
