### ISSUE TITLE
Class "Illuminate\Mail\Transport\Transport" not found Laravel 9 to 10 upgrade

### ISSUE THREAD

**Issue by TechhDan** [s-ichikawa/laravel-sendgrid-driver#171]
### What version of PHP and Laravel are you using?
PHP 8.1 and s-ichikawa/laravel-sendgrid-driver 3.0.4

### What did you do?
I updated Laravel 9 application to laravel 10.

### What did you expect to see?
Expected things to work as normal.

### What did you see instead?
When trying to use the forgot password using the sendgrid driver I receive an error.
```
Class "Illuminate\Mail\Transport\Transport" not found
```

**Comment by elliottpost** [comment]
I think you need to upgrade to v4.0+ of this app. see https://github.com/s-ichikawa/laravel-sendgrid-driver/issues/160
