### ISSUE TITLE
Advantages over SMTP

### ISSUE THREAD

**Issue by amsoell** [s-ichikawa/laravel-sendgrid-driver#19]
Apologies if an issue isn't the best place for this, but I was curious what advantages there might be in using this driver over [SendGrid's recommended way of sending email with Laravel](https://sendgrid.com/docs/Integrate/Frameworks/laravel.html) over their SMTP server. Trying to decide which way would ensure better efficiency and deliverability.

**Comment by amsoell** [comment]
So... no answer?

**Comment by s-ichikawa** [comment]
Sorry,  I seem to have misunderstood. I'm on the way to learning English.

I think using this package has two advantages.
・It require fewer messages to sent email less than using SMTP. [more detail](https://sendgrid.com/blog/web-api-or-smtp-relay-how-should-you-send-your-mail/)
・It can send without building MTA.

**Comment by sleenen** [comment]
@amsoell this package handles the settings of the smtp api headers internally, so you don't have to build it yourself like suggested on the Laravel page you mentioned. The link @s-ichikawa gave you about more details is an interesting read as well. They suggest there to use the API for sending mails. The efficiency difference in practice is probably not that big, but they explain in that document why API is a bit more efficient. Deliverability wise there should be no difference.

**Comment by s-ichikawa** [comment]
@amsoell 
If you no reply by tomorrow, I close this.

**Comment by amsoell** [comment]
@s-ichikawa That's fine, thanks for the clarification!
