### ISSUE TITLE
Substitutions

### ISSUE THREAD

**Issue by jcyusupov** [s-ichikawa/laravel-sendgrid-driver#21]
Hi! Thank you very much for package. It's very useful for me. But I have detected, that `substitutions` key doesn't work. It doesn't included in `personalizations` before sending. Could you please help me with it? Thank you!

**Comment by s-ichikawa** [comment]
Hi!
I just fixed this problem. try again!

example:
```
$message->embedData([
    'categories'       => ['newsletter_1'],
    'personalizations' => [
        [
            'substitutions' => [
                '%fname%' => 'recipient1',
            ],
        ],
    ],
], 'sendgrid/x-smtpapi');
```
