### ISSUE TITLE
Reply to header not coming through

### ISSUE THREAD

**Issue by sleenen** [s-ichikawa/laravel-sendgrid-driver#23]
When setting reply to, I don't see the corresponding header when I receive an email. 

```
$message->setReplyTo('info@example.com');
```

Is this lost somewhere?

**Comment by eightyfive** [comment]
Hi,

I just created a pull-request with the fix:
https://github.com/s-ichikawa/laravel-sendgrid-driver/pull/24

You can always use my fork temporarily. Before a fix is published.

Cheers,
Ben

**Comment by sleenen** [comment]
Thank you @eightyfive 

Through this it came to my attention that I'm using the v2 version of the Sendgrid API. A fix for the SendgridTransport class might be a nice option too?

I am trying to refactor my mails so it will use v3.

**Comment by s-ichikawa** [comment]
#24 is merged now. thank you @eightyfive !

and supported v2.
but v2 is not supported "reply to name". you can use only reply email address.
https://sendgrid.com/docs/API_Reference/Web_API/mail.html

**Comment by sleenen** [comment]
Very nice, will update library and try it out

**Comment by eightyfive** [comment]
Would you consider publishing a new version of the package (1.1.2) with the fix on Packagist?

Thx.

**Comment by s-ichikawa** [comment]
omg, I forget to create a tag.
published v1.1.2 now !
