### ISSUE TITLE
Markdown update

### ISSUE THREAD

**Issue by chrsc** [s-ichikawa/laravel-sendgrid-driver#32]
In Laravel 5.3 you need to edit config/services.php and add the sendgrid service.

`
    'sendgrid' => [
        'api_key' => env('SENDGRID_API_KEY'),
    ],
`

Cheers,
Chris

**Comment by s-ichikawa** [comment]
Thanks @chrsc 
It means that file name in README is wrong?
ng) service.php (now)
ok) services.php
