### ISSUE TITLE
how to use a transactional template

### ISSUE THREAD

**Issue by orlandomota** [s-ichikawa/laravel-sendgrid-driver#35]

**Comment by s-ichikawa** [comment]
# example

A transactional template that registered at The Sendgrid web page.
```
Hi,

<%body%>

Thanks,
:myname
```

code in laravel
```
\Mail::send('emails.embed_body_variable', [], function (Message $message) {
    $message
        ->subject('embed subject variable')
        ->from('ichikawa.shingo.0829@gmail.com', 's-ichikawa')
        ->to([
            'ichikawa.shingo.0829@gmail.com',
        ])
        ->replyTo('ichikawa.shingo.0829+replyto@gmail.com', 'おれだ！')
        ->embedData([
            'personalizations' => [
                [
                    'substitutions' => [
                        ':myname' => 's-ichikawa',
                    ],
                ],
            ],
            'template_id'      => '0f35ca1c-db1f-4953-98ab-7aeeb73d1818',
        ], 'sendgrid/x-smtpapi');
});
```

email template
resources/views/emails/embed_body_variable.blade.php
```
body embed template
```

# result
recive mail
```
Subject: New embed subject variable
Body:
Hi,
 
body embed template
 
Thanks,
s-ichikawa
```

**Comment by orlandomota** [comment]
in the rute for use file is
use Sichikawa\LaravelSendgridDriver\ [what name file is here] ;

2016-11-19 8:17 GMT-06:00 Shingo Ichikawa <notifications@github.com>:

**Comment by s-ichikawa** [comment]
you don't have to write use sentence.
this library is auto-loaded by adding to providers in config/app.

please read once README.

**Comment by b8ne** [comment]
Hey @s-ichikawa just wondering, if we are using a sendgrid template, why do we still want to attach a blade template? Can data be sent with no blade template?

**Comment by s-ichikawa** [comment]
Sorry, it is impossible now. because if you send without a template, thrown InvalidArgumentException in Illuminate/Mailer.
If someone found a way to sent without the template, I would fine do it.

do you have any idea?
