### ISSUE TITLE
Method [embedData] does not exist on mailable.

### ISSUE THREAD

**Issue by desmillicious** [s-ichikawa/laravel-sendgrid-driver#43]
Hi folks this driver is not compatible using the `Mailable` Method in Laravel 5.3 (see docs [here](https://laravel.com/docs/5.3/mail#generating-mailables))

The Laravel method uses its own `build` function which doesn't support the `embedData`.

Might be worth mentioning in the docs, or considering refactoring to extend the Mailable class?

**Comment by s-ichikawa** [comment]
I think to add a Trait for SendGrid API setting.

I pushed to dev branch a little while ago.
but, I will merge these after ready to tests and README.

**Comment by desmillicious** [comment]
Hi @s-ichikawa this is not working still, I have tried the new mailable and I am getting an error:

`BadMethodCallException in Mailable.php line 525:
Method [sengrid] does not exist on mailable.`

Am I doing something wrong? I have followed the setup instructions for 5.1~, but found I also needed to add
```
'driver' => env('MAIL_DRIVER', 'sendgrid'),
```
to the `config/mail.php` (which is an instruction from the **Lumen** section of your Readme) even though we are not using Lumen

Also on the Mailable I need to also `use Illuminate\Mail\Mailable;` otherwise an error is thrown:
```FatalErrorException in Welcome.php line 15:
Class 'App\Mail\Mailable' not found```

So my Mailable looks like:
```
<?php

namespace App\Mail;
use Illuminate\Bus\Queueable;
// use Illuminate\Mail\Mailable;
use Sichikawa\LaravelSendgridDriver\SendGrid;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class Welcome extends Mailable
{
  use Sendgrid, Queueable, SerializesModels;

  public function build()
    {
        return $this
                    ->view('emails.account.welcome')
                    ->subject('Welcome')
                    ->sengrid([
                        'template_id' => '4f36c1c9-6964-4aa5-b388-caa81b334c26'
                        ]);
    }
}

```

But throws: `BadMethodCallException in Mailable.php line 525:
Method [sengrid] does not exist on mailable.`

Any help appreciated!

**Comment by s-ichikawa** [comment]
Hi @desmillicious 
It is because wrong method name.
please try to change `sengrid` to `sendgrid`

**Comment by desmillicious** [comment]
oh dear, how embarrassing
thank you!

**Comment by desmillicious** [comment]
(working fine!)
