### ISSUE TITLE
ClientException on PasswordReset feature

### ISSUE THREAD

**Issue by johnatancabral** [s-ichikawa/laravel-sendgrid-driver#44]
When using laravel default password reset form to send notification for user email we get this ClientException error

![image](https://cloud.githubusercontent.com/assets/24550026/22424227/c854a442-e6dc-11e6-900a-0ca832dd8793.png)

Do we need to put additional configuration for it to work?

**Comment by s-ichikawa** [comment]
The request is missed a "from" parameter.
please, check your "from" configure in config/mail.php.

**Comment by johnatancabral** [comment]
thanks! problem solved.
