### ISSUE TITLE
Call to undefined method GuzzleHttp\Message\Response::getHeaderLine()

### ISSUE THREAD

**Issue by cyberiano** [s-ichikawa/laravel-sendgrid-driver#46]
I have this error using guzzle 5.3.1 

Call to undefined method GuzzleHttp\Message\Response::getHeaderLine() in /.../vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridV3Transport.php:69

In your composer.json version 5.3 appears to be supported, right?

```
"require": {
        "illuminate/mail": "~5.1",
        "guzzlehttp/guzzle": "~5.3|~6.2"
},
```

**Comment by s-ichikawa** [comment]
Thanks, I just merged revise for resolved this problem.
