### ISSUE TITLE
Readme Formatting broken

### ISSUE THREAD

**Issue by desmillicious** [s-ichikawa/laravel-sendgrid-driver#48]
Hey there I think the formatting on your Readme is broken?

**Comment by s-ichikawa** [comment]
Hi, I don't know where is broken.
Would you create a Pull Request, or tell how to revise?

**Comment by s-ichikawa** [comment]
Thank you, I'm going to correct in few days.

**Comment by s-ichikawa** [comment]
I correct now.
thank you for your issue.

**Comment by desmillicious** [comment]
no problem
