### ISSUE TITLE
Laravel send mail via v3 api

### ISSUE THREAD

**Issue by d3simic** [s-ichikawa/laravel-sendgrid-driver#62]
I have an "base64_encode() expects parameter 1 to be string, array given" error after using v3 example.

\Mail::send('view', [], function (Message $message) {
    	$message
	        ->to('...')
	        ->from('...')
	        ->replyTo('...')
	        ->embedData([
	            'personalizations' => [
	                [
	                    'to' => [
	                        'email' => '...',
	                        'name' => '...',
	                    ],
	                    'substitutions' => [
	                        '-name-' => '...',
	                        '-body-' => '...',
	                    ],
	                ],
	            ],
	        ], 'sendgrid/x-smtpapi');
	});
(... - replaced real data)

and i have set sendgrid array in config/services.php

'sendgrid' => [
        'api_key' => env('SENDGRID_API_KEY'),
        'version' => 'v3',
    ],
env file has api key.

Also i have follow installation of package for Laravel 5.1~

Please help.

Update:
Tryed same code with 5.1. version of laravel and it is working

**Comment by s-ichikawa** [comment]
I tried laravel5.1~5.4, but couldn't reproduce it.
You shoud try 'composer update'.
