### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by liepaja** [s-ichikawa/laravel-sendgrid-driver#63]
Updating to laravel 5.5 brings new swiftmailer dependency 6.0< and brings error:

> Declaration of Sichikawa\LaravelSendgridDriver\Transport\SendgridV3Transport::send(Swift_Mime_Message $message, &$failedRecipients = NULL) must be compatible with Swift_Transport::send(Swift_Mime_SimpleMessage $message, &$failedRecipients = NULL)

**Comment by liepaja** [comment]
So the problem is that laravel 5.5 requires swiftmailer/swiftmailer ~6.0, and some parts are changed there

**Comment by s-ichikawa** [comment]
@liepaja 
Thank you for your issue.
I just fix and push a new version sources.
Please try `"s-ichikawa/laravel-sendgrid-driver": "dev-dev"` !
If no problem, merge to master and tagging 2.0.

**Comment by liepaja** [comment]
Yep, it works

**Comment by magnetion** [comment]
Yep works, eagerly waiting 2.0 :)  Thanks for this package by the way.  We send out millions of emails via this package.

**Comment by s-ichikawa** [comment]
Thanks !
I just merged and tagged!
