### ISSUE TITLE
cannot install sendgrid driver v2 for laravel 5.4

### ISSUE THREAD

**Issue by congkevin** [s-ichikawa/laravel-sendgrid-driver#68]
I got errors below
Problem 1
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - s-ichikawa/laravel-sendgrid-driver 2.0.0 requires illuminate/mail ~5.5 -> satisfiable by illuminate/mail[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - s-ichikawa/laravel-sendgrid-driver 2.0.1 requires illuminate/mail ~5.5 -> satisfiable by illuminate/mail[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/mail v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/mail v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/mail v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/mail v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].
    - Installation request for s-ichikawa/laravel-sendgrid-driver ^2.0 -> satisfiable by s-ichikawa/laravel-sendgrid-driver[2.0.0, 2.0.1].

**Comment by s-ichikawa** [comment]
Sorry, v2 is support Laravel: ~5.5.
Please use v1.2.6 with Laravel: ~5.4.
https://github.com/s-ichikawa/laravel-sendgrid-driver/tree/1.2.6
