### ISSUE TITLE
Substitutions not working

### ISSUE THREAD

**Issue by bonevbb** [s-ichikawa/laravel-sendgrid-driver#71]
Hi, I added custom substitution
'substitutions' => [
                            '{{name}}' => 'test_name',
                            '{{email}}' => 'test_email'
],

but only email substitution worked. Why ? I need to add some custom substitutions.

**Comment by s-ichikawa** [comment]
Hi, I can't be reproduced.
I need your project detail.

**Comment by satoryu** [comment]
@bonevbb  do you mean that you wanna embed some values to your mail template via `substitutions` attribute? 
* [SendGrid API v3 - SendGrid Documentation | SendGrid](https://sendgrid.com/docs/API_Reference/api_v3.html)
* [Substitution Tags - SendGrid Documentation | SendGrid](https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html)

This package looks no support for substitution tags.

**Comment by satoryu** [comment]
Ah, sorry, I didn't see the following section of README:

* https://github.com/s-ichikawa/laravel-sendgrid-driver/blob/master/README.md#api-v3

@bonevbb did you try this?
