### ISSUE TITLE
how to use transactional template in laravel

### ISSUE THREAD

**Issue by tahseen2k8** [s-ichikawa/laravel-sendgrid-driver#75]
Hi first of all very nice plugin for use really very thankful for your efforts
i am facing challenge to use transnational template which exist on send-grid dashboard i want to send email by using these templates .i have integrated this plugin and sending default email mechanism . but unable to send template email . that will be great if you share a sample payload or example if possible 
below is my mailable  code 

 public function build()
    {
        return $this
            ->view('email.testemail')
            ->subject('subject')
            ->from('from@example.com')
            ->to(['abc@gmail.com'])
            ->sendgrid([
                'personalizations' => [
                    [
                        'substitutions' => [
                            ':myname' => 's-ichikawa',
                        ],
                        'templates' =>[
                            'settings' =>[
                                'enable' =>1,
                                'template_id'=> "template_id"

                            ]
                        ]
                    ],
                ],
            ]);

    }

**Comment by s-ichikawa** [comment]
Please try like below
https://github.com/s-ichikawa/laravel53/blob/master/app/Console/Commands/MailSample.php#L61

**Comment by tahseen2k8** [comment]
thanks for quick reply but again i have to set a View there as you did and it is again sending email template from view 
 Mail::send('email.testemail', [
            'img_src' => resource_path('docs/sendgrid.png')
        ], function ($message) use ($data) {
            $message
                ->subject('embed subject variable')
                ->from('admin@gmail.com', 'admin')
                ->to([
                    'tahseen@gmail.com',
                ])
                ->embedData(json_encode([
                    'personalizations' => [
                        [
                            'substitutions' => [
                                ':myname' => 'test',
                            ],
                        ],
                    ],
                    'template_id'      => '45cc7426-3814-4289-af73-xxxxxxxx',
                

                ]), 'sendgrid/x-smtpapi')
            ;
        });

**Comment by s-ichikawa** [comment]
OK, Please try remove `json_encode()`.
```
->embedData([
    'personalizations' => [
        [
            'substitutions' => [
                ':myname' => 'test',
            ],
        ],
    ],
    'template_id'      => '45cc7426-3814-4289-af73-xxxxxxxx',
], 'sendgrid/x-smtpapi');
```

**Comment by tahseen2k8** [comment]
thanks it works like charm thanks alot

**Comment by nanophp** [comment]
@s-ichikawa hi I'm tryin' 

`        Mail::send([], [], function (Message $message) {
            $message
                ->to($this->data['to'])
                ->from('noreply@thecompass.travel')
                ->subject('Invoice')
                ->embedData(json_encode([
                    'personalizations' => [
                        [
                            'dynamic_template_data' => [
                                'branch_name' => 'amk',
                            ],
                        ],
                    ],
                    'template_id' => 'xxxxxx',
                ]), SendgridTransport::SMTP_API_NAME);
        });`

but I got an email like sendgrid_x-smtpapi type file and I see such kinda json

**Comment by narendralussspacetech** [comment]
@s-ichikawa I'm unable to post `unique_args` using `embedData()`. You can see my Mailable code given below:

```
use SendGrid;
public function build()
{
return $this->from('support@domain.com', $from_name)
                    ->subject($subject)
                    ->markdown('email.review.review-request')
                    ->embedData(self::sgEncode([
                        'personalizations' => [
                            [
                                'substitutions' => [
                                    ':myname' => 'test',
                                ],
                            ],
                            'categories' => ['category_a_1', 'category_b_1'],
                        ],
                        'unique_args' => [
                            'user_id' => 'asdasdasdasdasd123'
                        ],
                        'categories' => ['category_a_1', 'category_b_1'],
                    ]), 'sendgrid/x-smtpapi');
}
```
I was check [ApiSimpleText.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimpleText.php), [ApiSimpleMailable.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimpleMailable.php), [ApiSimple.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimple.php) and [ApiMultiplePersonalizations.php](https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiMultiplePersonalizations.php) before jump to here.

Could you please help me sort this out ASAP. :)
