### ISSUE TITLE
400 Bad Request When Template Id is Provided 

### ISSUE THREAD

**Issue by syclone** [s-ichikawa/laravel-sendgrid-driver#76]
If I leave my view empty I get the below error message even though I am using SendGrid's template system.

`
Client error: POST https://api.sendgrid.com/v3/mail/send resulted in a 400 Bad Request response:\n
{"errors":[{"message":"The content value must be a string at least one character in length.","field":"content.0.value"," (truncated...)
`

The template has all the content / html for the email and therefore I do not need to generate any body from the Laravel view. How can this be achieved?

Here is a sample of my code:

`
namespace App\Mail;

use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Sichikawa\LaravelSendgridDriver\SendGrid;

class PasswordReset extends Mailable {

	use Queueable, SerializesModels, SendGrid;

	public $user;
	public $password_reset_url;
	public $body = '';
	public $view = 'emails.body';

	public function __construct( $user, $token ) {
		$this->user               = $user;
		$this->password_reset_url = url( config( 'app.url' ) . route( 'password.reset', $token, false ) );
	}

	public function build() {

		return $this
			->to( [ $this->user->email ] )
			->sendgrid( [
				'template_id'      => "xxxx-xxxx-xxxx-xxxx-xxxx",
				'personalizations' => [
					[
						'substitutions' => [
							'%username%'           => $this->user->username,
							'%password_reset_url%' => $this->password_reset_url
						]
					],
				],
			] );

	}
}
`

If I do not specify any view I get the error message "Invalid View"

Note: View file body.blade.php is just {{ $body }}

Thanks for any help

**Comment by s-ichikawa** [comment]
Sorry for the late reply.

Now, view file has required some contents. but, has no required to use the contents by `<% body %>` in a transaction mail template.

You should create a dummy file. like below.

resources/views/mails/dummy.blade.php
```
dummy
```

or create cool Pull Request.

**Comment by syclone** [comment]
That's what I had to do as a work around. I created a view file **body.blade.php** with just {{ $body }}. Even though its not being used.
