### ISSUE TITLE
Have I to install and setup smtp for using this plugin?

### ISSUE THREAD

**Issue by PetroGromovo** [s-ichikawa/laravel-sendgrid-driver#85]
Hi,
Installing "s-ichikawa/laravel-sendgrid-driver": "~2.0" in my laravel 5.7 application
have I to install and setup smtp or other mail service(Apache2, ubuntu 18 under Digital Ocean)?

Thanks!

**Comment by s-ichikawa** [comment]
No, you don't need to install any mail service.
