### ISSUE TITLE
Not able to send attachment with email.

### ISSUE THREAD

**Issue by mhamzawaheed** [s-ichikawa/laravel-sendgrid-driver#86]
Using extension on with laravel 5.2 and sendgrid free account.
Is there any example to send email with attachment using this extension.
Currently, sendgrid email service is working without attachment.

**Comment by s-ichikawa** [comment]
Thank you for using this library.

Laravel5.2 example is this.
https://github.com/s-ichikawa/laravel52/blob/master/app/Console/Commands/SendGridSample.php#L58
