### ISSUE TITLE
How to get message id and if email id is not exist then also it return status code 200

### ISSUE THREAD

**Issue by rajanand53** [s-ichikawa/laravel-sendgrid-driver#9]

**Comment by s-ichikawa** [comment]
Even if SendGrid did not send mail actually,when Web API received a request to send mail, Web API replies a 200 code with JSON data. and, this JSON data contain only results. like '{message: "success"}'.
for the reason, you can't get message id by this library.

but if you use Event Notification function, it may be able to do it.
https://sendgrid.com/docs/API_Reference/Webhooks/event.html

**Comment by ilvalerione** [comment]
How can I establish a relationship between the event and the email I sent? 

Use case:
My users send two different newsletters to the same email address. (an email address registered to more newsletters)

When Sendgrid POST an event how can i understand which email refers?

**Comment by s-ichikawa** [comment]
You can use [categories and custom_args](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters).
(if you using API v2, these are [Category](https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html) and [Unique Argument](https://sendgrid.com/docs/API_Reference/SMTP_API/unique_arguments.html) )

example:
```
\Mail::send('emails.sendgrid_sample', [], function (Message $message) use ($user, $send_date) {
    $message
        ->subject('This is a test.')
        ->from('from@example.com')
        ->to('to@edample.com')
        ->embedData([
            'categories'  => ['newsletter_1'],
            'custom_args' => [
                'send_date' => '2016-10-01',
                'user_id'   => '123',
            ],
        ], 'sendgrid/x-smtpapi');
});
```

Sendgrid posted,

```
Route::post('/sendgrid/event', function (\Illuminate\Http\Request $request) {
    Log::info($request->all());
});
```

```
// to leave out some params
[
  0 => [
    'event' => 'delivered',
    'email' => 'to@edample.com',
    'send_date' => '2016-10-01',
    'category' =>
    array (
      0 => 'newsletter_1',
    ),
    'user_id' => '123',
  ],
  1 => [
    'event' => 'open',
    'email' => 'to@edample.com',
    'send_date' => '2016-10-01',
    'category' =>
    array (
      0 => 'newsletter_1',
    ),
    'user_id' => '123',
  ]
]
```

**Comment by ilvalerione** [comment]
Thank you so much! Very useful!

**Comment by webboy** [comment]
SG Message ID is not returned as JSON response from WebAPI, but it is returned along response headers (X-Message-Id).

Any idea how to fetch it?

**Comment by s-ichikawa** [comment]
@webboy 
I just testing in a dev branch.

This change will be able to fetch with registering a Tracking Class that has a sendPerformed function in ServiceProvider@boot().
like [this](https://github.com/s-ichikawa/laravel53/commit/c1061c43fba63739390db0fe8683c87dd4d8a8f8#diff-66e9f58de26f4aa2cfe24f984f8dcfe3R59).

but, only can use with Laravel5.3 and over.

**Comment by mailnike** [comment]
@s-ichikawa question - does your change now returns 'message id'?

**Comment by s-ichikawa** [comment]
@mailnike 
Yes, I did it.
Please refer the previous comment.
