### ISSUE TITLE
Variables not getting passed to Mail?

### ISSUE THREAD

**Issue by sukhcha-in** [s-ichikawa/laravel-sendgrid-driver#92]
Hello,
Why my variable `$name` and `$email` is not getting passed to Mail?
It throws: `Undefined variable: name`
Here is my code:
```
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Mail\Message;
use Sichikawa\LaravelSendgridDriver\SendGrid;
use Mail;

class MyController extends Controller
{
    public function testMail(Request $request) {
        $name = $request->name;
        $email = $request->email;
        
        Mail::send([], [], function (Message $message) {
            $message
                ->to($email)
                ->from(config('mail.from.address'), config('mail.from.name'))
                ->embedData([
                    'personalizations' => [
                        [
                            'dynamic_template_data' => [
                                'name' => $name,
                                'verificationid'  => 'XXX',
                            ],
                        ],
                    ],
                    'template_id' => 'XXX',
                ], SendgridTransport::SMTP_API_NAME);
        });
    }
}

```
If i try to hardcode `Email` and `Name` variable it throws:
```
Class 'App\Http\Controllers\SendgridTransport' not found
```

**Comment by s-ichikawa** [comment]
You should use `use` language construct.
see: https://www.php.net/manual/en/functions.anonymous.php

As following:
```:php
Mail::send([], [], function (Message $message) use ($name, $email) {
    ...
}
```

**Comment by sukhcha-in** [comment]
@s-ichikawa thanks for that info, SendgridTransport gives error:
```
"Class 'App\Http\Controllers\SendgridTransport' not found"
```
Do i need to create `SendgridTransport` Controller? What needs to be there in?

**Comment by sukhcha-in** [comment]
@s-ichikawa I fixed that by using `'sendgrid/x-smtpapi'` instead of `SendgridTransport`
Is this a good way to do this?

**Comment by s-ichikawa** [comment]
@sukhcha-in Yes, it is no problem too.
Or you can solve by correct `use namespace`.

**Comment by s-ichikawa** [comment]
Like a following:
https://github.com/s-ichikawa/laravel57/blob/master/app/Console/Commands/Mail/ApiSimple.php#L7

**Comment by sukhcha-in** [comment]
@s-ichikawa Great 😄  Thanks for this awesome library!
Is there any way to check JSON response that we get from sendgrid?
