### ISSUE TITLE
cc and bcc not working

### ISSUE THREAD

**Issue by carlluo** [s-ichikawa/laravel-sendgrid-driver#97]
I'm using the following method to call the method to send an email.

`Mail::to($request->email_address)->cc('address@email.com')->send(new EmailMessage($request));`

The email is sent correctly, but cc or bcc it doesn't work. I also don't get any errors so its hard to debug.

Can anyone help me out here?

**Comment by s-ichikawa** [comment]
What is the version of Laravel and this library?

**Comment by s-ichikawa** [comment]
<img width="1162" alt="スクリーンショット 2019-04-20 23 53 54" src="https://user-images.githubusercontent.com/3357107/56458920-991d8080-63c7-11e9-8d3d-e69e7117a26c.png">
At the least, my laravel 5.7 environment seems working.

https://github.com/s-ichikawa/laravel57/blob/master/app/Console/Commands/Mail/ApiSimpleMailable.php

**Comment by carlluo** [comment]
I'm using 5.5.43.

Would it be some setting on Sendgrid I need to switch on?

**Comment by s-ichikawa** [comment]
BTW did you use with Gmail address and the aliases?

In case that I tried by my Gmail address and two aliases. like the following:
- ichikawa.shingo.0829@gmail.com
- ichikawa.shingo.0829+cc@gmail.com
- ichikawa.shingo.0829+bcc@gmail.com

Seems like sending succeed.
<img width="1149" alt="スクリーンショット 2019-04-22 21 56 43" src="https://user-images.githubusercontent.com/3357107/56501397-9b0f4d00-6549-11e9-8ba0-fa3f87e0b64b.png">

But I could find only an email that not alias address in Gmail app.

**Comment by s-ichikawa** [comment]
> Would it be some setting on Sendgrid I need to switch on?

I think there is not especially configuration.

**Comment by carlluo** [comment]
I worked it out.

Silly me, I forgot to run the config:cache to reset.

It's working now. 

Thank you
