### ISSUE TITLE
SendGrid template_id not working.

### ISSUE THREAD

**Issue by nanophp** [s-ichikawa/laravel-sendgrid-driver#98]
Hi, thanks for the great package, 

I have some issues about using SendGrid templates. In another client, everything works fine.

`{
	"personalizations": [
		{
			"to" : [
				{
					"email" : "valehasadli@gmail.com", 
					"name": "Valeh Asadli"
				}
			],
			"dynamic_template_data": {
		        "branch_name": "Galiano"
	    	}
		}
	],
	"from": {
		"email" : "noreply@thecompass.travel",
		"name" : "Compass Travel"
	},
	"template_id" : "temp_idxxx"
}`

this JSON totally working fine postman client, variable passed and I get an email. 
But I facing this problem LARAVEL code.

`        Mail::send([], [], function (Message $message) {
            $message
                ->to($this->data['to'])
                ->from('noreply@thecompass.travel')
                ->subject('Invoice')
                ->embedData(
                    json_encode([
                        'personalizations' => [
                            [
                                'dynamic_template_data' => [
                                    'branch_name' => 'amk',
                                ],
                            ],
                        ],
                        'template_id' => 'xxxx',
                    ]),
                    SendgridTransport::SMTP_API_NAME
                );
        });`

I got an email but SMTP type file and JSON structure. How can I fix 

JOB FILE:

`<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Message;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\Mail;
//use App\Mail\SendReservationInvoice as SendReservationInvoiceMail;
use Sichikawa\LaravelSendgridDriver\SendGrid;
use Sichikawa\LaravelSendgridDriver\Transport\SendgridTransport;

class SendReservationInvoice implements ShouldQueue
{
    private $data;

    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, SendGrid;

    /**
     * SendReservationInvoice constructor.
     * @param array $data
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle(): void
    {
//        Mail::to($this->data['to'])
//            ->send(new SendReservationInvoiceMail($this->data));

        Mail::send([], [], function (Message $message) {
            $message
                ->to($this->data['to'])
                ->from('noreply@thecompass.travel')
                ->subject('Invoice')
                ->embedData(
                    json_encode([
                        'personalizations' => [
                            [
                                'dynamic_template_data' => [
                                    'branch_name' => 'amk',
                                ],
                            ],
                        ],
                        'template_id' => 'xxxx',
                    ]),
                    SendgridTransport::SMTP_API_NAME
                );
        });
    }
}
`

**Comment by s-ichikawa** [comment]
@nanophp Hi, What is your laravel version?
My laravel 5.7 code is working with the dynamic template. like following:
https://github.com/s-ichikawa/laravel57/blob/master/app/Console/Commands/Mail/ApiSimple.php#L43

**Comment by nanophp** [comment]
> @nanophp Hi, What is your laravel version?
> My laravel 5.7 code is working with the dynamic template. like following:
> https://github.com/s-ichikawa/laravel57/blob/master/app/Console/Commands/Mail/ApiSimple.php#L43

Hi, my laravel app version is 5.8.16.

**Comment by nanophp** [comment]
@s-ichikawa I'm wanna using template id without the laravel view.

**Comment by nanophp** [comment]
@s-ichikawa I got such email
![Screen Shot 2019-05-13 at 6 22 12 AM](https://user-images.githubusercontent.com/7104643/57592403-8bcb6000-7547-11e9-9511-9f6957e71022.png)

**Comment by nanophp** [comment]
> @s-ichikawa I got such email
> ![Screen Shot 2019-05-13 at 6 22 12 AM](https://user-images.githubusercontent.com/7104643/57592403-8bcb6000-7547-11e9-9511-9f6957e71022.png)

`app('mailer')->send([], [], function (Message $message) {
            $message
                ->subject('Invoice.')
                ->to($this->data['to'])
                ->from('noreply@thecompass.travel')
                ->embedData(self::sgEncode([
                    'personalizations' => [
                        [
                            'to' => [
                                'email' => $this->data['to'],
                                'name'  => 'TheCompass Digital',
                            ],
                            'dynamic_template_data' => [
                                'branch_name' => 'Shingo Ichikawa',
                            ],
                        ],
                    ],
                    'template_id' => 'd-435bab43217e4bdaae20af7ee962f46e'
                ]), SendgridTransport::SMTP_API_NAME);
        });`

**Comment by s-ichikawa** [comment]
I tried with 5.8, but worked well.
https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimple.php#L45
<img width="363" alt="スクリーンショット 2019-05-13 20 03 35" src="https://user-images.githubusercontent.com/3357107/57616796-13ea4d80-75ba-11e9-91c6-5369ba414d43.png">

Is your `MAIL_DRIVER` value  in .env file seted `smtp`?
You must edit to `sendgrid` for using this library.
https://github.com/s-ichikawa/laravel-sendgrid-driver#configure

**Comment by nanophp** [comment]
> https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimple.php#L45

@s-ichikawa Yes, `MAIL_DRIVER` setted as `smtp`

`
MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=my_username
MAIL_PASSWORD=my_pass
MAIL_ENCRYPTION=tls
MAIL_FROM_NAME="Compass Digital"
MAIL_FROM_ADDRESS=noreply@thecompass.travel

SENDGRID_ENDPOINT=https://api.sendgrid.com/v3/mail/send`

<img width="940" alt="Screen Shot 2019-05-13 at 3 33 30 PM" src="https://user-images.githubusercontent.com/7104643/57618545-cd362c80-7594-11e9-831c-8fc6173a7199.png">


Also, my current code looks like this

`        app('mailer')->send([], [], function (Message $message) {
            $message
                ->subject('Invoice.')
                ->to($this->data['to'])
                ->from('noreply@thecompass.travel')
                ->embedData(self::sgEncode([
                    'personalizations' => [
                        [
                            'to' => [
                                'email' => $this->data['to'],
                                'name' => 'The Compass Digital',
                            ],
                            'dynamic_template_data' => [
                                'branch_name' => $this->data['branch_name'],
                            ],
                        ],
                    ],
                    'template_id' => $this->data['template_id']
                ]), SendgridTransport::SMTP_API_NAME);
        });`

**Comment by nanophp** [comment]
> I tried with 5.8, but worked well.
> https://github.com/s-ichikawa/laravel58/blob/master/app/Console/Commands/Mail/ApiSimple.php#L45
> <img alt="スクリーンショット 2019-05-13 20 03 35" width="363" src="https://user-images.githubusercontent.com/3357107/57616796-13ea4d80-75ba-11e9-91c6-5369ba414d43.png">
> 
> Is your `MAIL_DRIVER` value in .env file seted `smtp`?
> I got the same case in this way.
> <img alt="スクリーンショット 2019-05-13 20 33 16" width="297" src="https://user-images.githubusercontent.com/3357107/57618392-39795600-75be-11e9-9001-7683f2c5be71.png">
> 
> You must edit to `sendgrid` for using this library.
> https://github.com/s-ichikawa/laravel-sendgrid-driver#configure

I need to receive sendgrid template as an email

**Comment by s-ichikawa** [comment]
Please, change `MAIL_DRIVER` value to `sendgrid` from `smtp`.
In setted `smtp`, you are not able to call this library.

**Comment by nanophp** [comment]
@s-ichikawa Thankssssss!!! :)))))) It works!!!!

**Comment by Diksha95-et** [comment]
hey i get email like this
![image](https://user-images.githubusercontent.com/56334189/69627473-a80c9580-1070-11ea-9a7b-99b47cea29cd.png)
 and my error looks like this please give me any solution
![image](https://user-images.githubusercontent.com/56334189/69627532-c8d4eb00-1070-11ea-9183-62c53311a321.png)
